# Generated by Django 4.0.6 on 2022-08-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0004_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tees',
            field=models.CharField(choices=[('White', 'White'), ('Blue', 'Blue'), ('Red', 'Red'), ('Black', 'Black')], default='White', max_length=6),
        ),
    ]
