# Generated by Django 4.0.6 on 2022-08-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0005_alter_course_tees'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='back_yardage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='front_yardage',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
