# Generated by Django 4.0.6 on 2022-08-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0006_course_back_yardage_course_front_yardage'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='back_par',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='front_par',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
