# Generated by Django 4.0.6 on 2022-08-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0008_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='slope',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
