# Generated by Django 4.0.6 on 2022-08-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0010_alter_course_course_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
