# Generated by Django 4.1 on 2022-08-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0011_alter_course_course_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='match',
            field=models.IntegerField(default=0),
        ),
    ]
