# Generated by Django 4.1 on 2022-08-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0012_round_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='abbreviation',
            field=models.CharField(default='MCC', max_length=10),
            preserve_default=False,
        ),
    ]
