# Generated by Django 4.0.6 on 2022-08-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0013_course_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='has_rounds',
            field=models.BooleanField(default=False),
        ),
    ]
