# Generated by Django 4.0.6 on 2022-08-03 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='user',
            new_name='golfer',
        ),
        migrations.AddField(
            model_name='course',
            name='tees',
            field=models.CharField(default='White', max_length=10),
        ),
        migrations.AddField(
            model_name='round',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
