# Generated by Django 4.0.6 on 2022-08-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_rename_user_round_golfer_course_tees_round_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hole',
            old_name='number',
            new_name='tee',
        ),
        migrations.AddField(
            model_name='course',
            name='par',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='yardage',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
