# Generated by Django 4.1 on 2022-08-08 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0007_course_back_par_course_front_par'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golfers_scores', to=settings.AUTH_USER_MODEL)),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holes_scores', to='golf.hole')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_scores', to='golf.round')),
            ],
        ),
    ]
