# Generated by Django 4.0.6 on 2022-08-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0015_remove_course_has_rounds_user_has_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='solo_round',
            field=models.BooleanField(default=False),
        ),
    ]
